odom_topic: /pf/pose/odom
drive_topic: /drive

# Pure pursuit parameters
lookahead_distance: 1.0 # meters
end_threshold: 0.35 # meters
speed: 4.0
kp: 0.4
ki: 0.0
kd: 0.01

# Path planning parameters
num_vertices: 1000
num_edges_per_node: 20
num_sample_rrt: 10000
make_random_graph: false
graph_discretization: 10 # pixels
